# Generated by Django 3.0.7 on 2020-06-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_description', models.CharField(max_length=126, verbose_name='Menu Description')),
                ('cart_description', models.CharField(max_length=126, verbose_name='Menu Description')),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Large Price')),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Small Price')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126, verbose_name='Name of Topping')),
            ],
        ),
        migrations.CreateModel(
            name='OneSizeMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
                ('entree_type', models.CharField(choices=[('pasta', 'Pasta'), ('salad', 'Salad')], default='salad', max_length=50, verbose_name='Entree Type')),
            ],
            options={
                'verbose_name': 'One Size',
                'verbose_name_plural': 'One Size Entrees',
            },
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='PlatterMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
            ],
            options={
                'verbose_name': 'Platter',
                'verbose_name_plural': 'Platters',
            },
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='SandwichMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
                ('extra_cheese', models.BooleanField(verbose_name='Extra Cheese')),
                ('wit', models.BooleanField(verbose_name='Wit')),
                ('mushrooms', models.BooleanField(verbose_name='Mushrooms')),
                ('peppers', models.BooleanField(verbose_name='Peppers')),
            ],
            options={
                'verbose_name_plural': 'Steaks and Hoagies',
            },
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='PizzaMenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
                ('toppings', models.PositiveSmallIntegerField(verbose_name='Number of Toppings')),
                ('pizza_type', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=50, verbose_name='Pizza Type')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
                'unique_together': {('pizza_type', 'toppings')},
            },
            bases=('menu.menuitem',),
        ),
    ]
