# Generated by Django 3.0.7 on 2020-06-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='cart_description',
            field=models.CharField(max_length=126, verbose_name='Cart Description'),
        ),
    ]
