# Generated by Django 3.0.7 on 2020-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200615_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onesizemenuitem',
            options={'verbose_name': 'One Size', 'verbose_name_plural': 'One Size Entrees'},
        ),
        migrations.AlterModelOptions(
            name='pizzamenuitem',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='plattermenuitem',
            options={'verbose_name': 'Platter', 'verbose_name_plural': 'Platters'},
        ),
        migrations.AlterModelOptions(
            name='sandwichmenuitem',
            options={'verbose_name_plural': 'Steaks and Hoagies'},
        ),
        migrations.AddField(
            model_name='onesizemenuitem',
            name='entree_type',
            field=models.CharField(choices=[('pasta', 'Pasta'), ('salad', 'Salad')], default='salad', max_length=50, verbose_name='Entree Type'),
        ),
        migrations.AlterField(
            model_name='pizzamenuitem',
            name='pizza_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=50, verbose_name='Pizza Type'),
        ),
    ]
